# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date + '%Y-%m-%d-%H:%M:%S.%3NZ')"

    - name: Tag commit
      uses: tvdias/github-tagger@v0.0.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        tag: "${{ steps.date.outputs.date }}"

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "build/2rm"
        tag: "${{ steps.date.outputs.date }}"
